services:
  - type: web
    name: wbs-sukoharjo
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: true
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
